# templates/postgribbit.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgribbit-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: postgribbit
  template:
    metadata:
      labels:
        app: postgribbit
    spec:
      containers:
        - name: postgribbit
          image: ofirtako.jfrog.io/docker-images/jfrog_postgribbit:latest
          env:
            # - name: POSTGRES_USER
            #   valueFrom:
            #     secretKeyRef:
            #       name: postgres-secret
            #       key: username
            # - name: POSTGRES_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: postgres-secret
            #       key: password
          envFrom:
            - configMapRef:
               name: envvars


---
apiVersion: v1
kind: Service
metadata:
  name: postgribbit-service
spec:
  selector:
    app: postgribbit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: ClusterIP

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: postgribbit
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: postgribbit
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 300
