apiVersion: v2
name: jfrog-services-app
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"


# dependencies:
#   - name: postgresql
#     version: 13.0.0
#     repository: file://postgresql-13.0.0.tgz
#   - name: pondpulse
#     version: 0.1.0
#     repository: file://pondpulse-0.1.0.tgz
#   - name: flytrap
#     version: 0.1.0
#     repository: file://flytrap-0.1.0.tgz
#   - name: postgribbit
#     version: 0.1.0
#     repository: file://postgribbit-0.1.0.tgz

dependencies:
  - name: postgresql
    version: 0.1.0
    repository: file://charts/postgresql-0.1.0.tgz
  - name: pondpulse
    version: 0.1.0
    repository: file://charts/pondpulse-0.1.0.tgz
  - name: flytrap
    version: 0.1.0
    repository: file://charts/postgribbit-0.1.0.tgz
  - name: postgribbit
    version: 0.1.0
    repository: file://charts/flytrap-0.1.0.tgz


