# templates/pondpulse.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pondpulse-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pondpulse
  template:
    metadata:
      labels:
        app: pondpulse
    spec:
      imagePullSecrets:
      - name: my-jfrog-secret
      containers:
        - name: pondpulse
          image: ofirtako.jfrog.io/docker-images/jfrog_pondpulse:latest
          ports:
            - containerPort: 5001
          readinessProbe:
            httpGet:
              path: /microservices
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /microservices
              port: 5001
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: pondpulse-service
spec:
  selector:
    app: pondpulse
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: envvars
data:
  pondpulse_url: http://pondpulse-service/microservices
  db_name: mydb
  db_port: "5432"

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pondpulse
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pondpulse
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 300
