name: Build and Push Docker Images



on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Push Pondpulse Docker Image
        working-directory: pondpulse
        env:
          DOCKER_REGISTRY: https://ofirtako.jfrog.io/artifactory/docker-images/jfrog_pondpulse/
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t $DOCKER_REGISTRY/pondpulse:latest .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
          docker push $DOCKER_REGISTRY/pondpulse:latest

      - name: Build and Push Flytrap Docker Image
        working-directory: flytrap
        env:
          DOCKER_REGISTRY: https://ofirtako.jfrog.io/artifactory/docker-images/jfrog_flytrap/
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t $DOCKER_REGISTRY/flytrap:latest .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
          docker push $DOCKER_REGISTRY/flytrap:latest

      - name: Build and Push Postgribbit Docker Image
        working-directory: postgribbit
        env:
          DOCKER_REGISTRY: https://ofirtako.jfrog.io/artifactory/docker-images/jfrog_postgribbit/
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t $DOCKER_REGISTRY/postgribbit:latest .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
          docker push $DOCKER_REGISTRY/postgribbit:latest

